DROP TABLE IF EXISTS BlogPost CASCADE;
CREATE TABLE BlogPosts (
    PostID INT PRIMARY KEY,
    UserID INT,
    Title VARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    Tags VARCHAR(255),
    PublicationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(UserID)
);
