DROP TABLE IF EXISTS BlogPosts CASCADE;
CREATE TABLE BlogPosts (
    PostID SERIAL PRIMARY KEY NOT NULL,
    BlogPostUserID int  NOT NULL,
    Title VARCHAR(255) NOT NULL,
    Content TEXT NOT NULL,
    Tags VARCHAR(255),
    PublicationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (BlogPostUserID) REFERENCES Users(Id)
);


