DROP TABLE IF EXISTS Comments CASCADE;
CREATE TABLE Comments (
    CommentID SERIAL PRIMARY KEY NOT NULL,
    CommentUserID INT,
    CommentPostID INT,
    Text TEXT NOT NULL,
    CreationDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (CommentUserID) REFERENCES Users(Id),
    FOREIGN KEY (CommentPostID) REFERENCES BlogPosts(PostID) ON DELETE CASCADE
);
